# Generated by Django 5.1.3 on 2024-12-07 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0003_rename_delete_category_is_delete_and_more'),
        ('User', '0005_alter_gift_cart_code_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('p', 'percentage'), ('a', 'amount')], max_length=1)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gift_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('discount_type', models.CharField(choices=[('p', 'percentage'), ('a', 'amount')], max_length=1)),
                ('min_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('value', models.DecimalField(decimal_places=0, max_digits=10)),
                ('end_date', models.DateField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
