# Generated by Django 5.1.3 on 2024-12-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift_cart',
            name='product',
        ),
    ]
