# Generated by Django 5.1.3 on 2025-01-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0002_remove_gift_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift_cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
