# Generated by Django 5.1.2 on 2024-12-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.DecimalField(decimal_places=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='gift_cart',
            name='code',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gift_cart',
            name='max_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gift_cart',
            name='min_amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gift_cart',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
