# Generated by Django 5.1.2 on 2024-12-02 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_address_postal_code_alter_gift_cart_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=19, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+989xxxxxxxxx' or '09xxxxxxxxx'.", regex='^(\\+98|0)?9\\d{9}$')]),
        ),
    ]
