# Generated by Django 5.1.2 on 2024-12-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_price'),
        ('User', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift_cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
    ]
