# Generated by Django 5.1.2 on 2024-12-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_gift_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift_cart',
            name='code',
            field=models.DecimalField(decimal_places=0, max_digits=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
