# Generated by Django 5.1.3 on 2024-12-17 12:38

import User.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_rename_delete_address_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='math1234&', max_length=20, unique=True, validators=[User.validator.is_valid_password]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='new', max_length=100),
            preserve_default=False,
        ),
    ]
