# Generated by Django 5.1.3 on 2024-12-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0001_initial'),
        ('Orders', '0008_rename_delete_orderitem_is_delete_and_more'),
        ('User', '0012_rename_user_customuser'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
