# Generated by Django 5.1.3 on 2024-12-19 08:47

import User.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, unique=True, validators=[User.validator.is_valid_password]),
        ),
    ]
