# Generated by Django 5.1.3 on 2025-01-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_alter_user_date_of_birth_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiroGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('picture_1', models.ImageField(upload_to='hiro/')),
                ('picture_2', models.ImageField(upload_to='hiro/')),
                ('picture_3', models.ImageField(upload_to='hiro/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
