# Generated by Django 5.1.3 on 2025-01-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_hirogallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HiroGallery',
            new_name='HeroGallery',
        ),
    ]
