# Generated by Django 5.1.3 on 2025-01-07 08:15

import User.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_rename_hirogallery_herogallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, validators=[User.validator.is_valid_password]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('m', 'manager'), ('c', 'customer'), ('s', 'supervisor')], max_length=1),
        ),
    ]
