# Generated by Django 5.1.3 on 2025-01-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, unique=True),
        ),
    ]
