# Generated by Django 5.1.2 on 2024-12-01 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_status', models.CharField(choices=[('paid', 'paid'), ('progressing', 'progressing'), ('canceled', 'canceled')], max_length=11)),
                ('city', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('postal_code', models.DecimalField(decimal_places=2, max_digits=17)),
                ('address_description', models.CharField(max_length=150)),
                ('send_status', models.CharField(choices=[('p', 'Processing'), ('l', 'Leaving the warehouse'), ('d', 'Delivered')], max_length=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gift_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.gift_cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orders')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
