# Generated by Django 5.1.2 on 2024-12-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='postal_code',
            field=models.DecimalField(decimal_places=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
