# Generated by Django 5.1.2 on 2024-12-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_alter_orderitem_price_at_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
