# Generated by Django 5.1.2 on 2024-12-02 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_orderitem_price_at_order'),
        ('User', '0002_alter_address_postal_code_alter_gift_cart_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.address'),
            preserve_default=False,
        ),
    ]
