# Generated by Django 5.1.2 on 2024-12-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
    ]
