# Generated by Django 5.1.3 on 2024-12-07 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0001_initial'),
        ('Orders', '0007_alter_orderitem_price_at_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='gift_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Discount.gift_cart'),
        ),
    ]
