# Generated by Django 5.1.3 on 2024-12-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_rename_delete_orderitem_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='receiver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
