# Generated by Django 5.1.3 on 2024-12-29 08:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_orders_receiver'),
        ('User', '0017_alter_user_date_of_birth_alter_user_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('user', 'address')},
        ),
    ]
