# Generated by Django 5.1.3 on 2024-12-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_alter_orders_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together=set(),
        ),
    ]
