# Generated by Django 5.1.3 on 2025-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0011_alter_orders_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='postal_code',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='street_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
