# Generated by Django 5.1.3 on 2025-01-10 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0012_alter_orders_address_description_alter_orders_city_and_more'),
        ('Products', '0010_remove_product_inventory_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_diversity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.diversity'),
            preserve_default=False,
        ),
    ]
