# Generated by Django 5.1.3 on 2024-12-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_discount',
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
