# Generated by Django 5.1.3 on 2024-12-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_delete_category_is_delete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='product',
            new_name='image',
        ),
    ]
