# Generated by Django 5.1.3 on 2024-12-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_rename_product_gallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='product',
        ),
    ]
