# Generated by Django 5.1.3 on 2024-12-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_rename_image_gallery_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(upload_to='.\\online shop\\Front_Online_Shop\\static\\img\x07bout-hero.svg'),
        ),
    ]
