# Generated by Django 5.1.3 on 2024-12-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_gallery_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
